objects:
  - path: deploy.yaml
    value:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: my-app
      spec:
        replicas: 1
        containers:
          - image: dev-v10.10.2
            name: my-app
  - path: kustomization.yaml
    value:
      apiVersion: kustomize.config.k8s.io/v1beta1
      kind: Kustomization
      resources:
        - deployment.yaml
